import Head from 'next/head';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../theme/theme";
import { Box, Button, Container, TextField, Typography } from '@mui/material';
import AddBusinessRoundedIcon from '@mui/icons-material/AddBusinessRounded';
import EditRoundedIcon from '@mui/icons-material/EditRounded';
import DeleteForeverRoundedIcon from '@mui/icons-material/DeleteForeverRounded';
import AssignmentRoundedIcon from '@mui/icons-material/AssignmentRounded';
import LoginRoundedIcon from '@mui/icons-material/LoginRounded';
import PowerSettingsNewRoundedIcon from '@mui/icons-material/PowerSettingsNewRounded';
import MenuItem from '@mui/material/MenuItem';
import ModalForm from '../components/FormEmpresa/ModalForm';
import AlertDialog from '../components/AlertDialog';
import { useRouter } from "next/router";
import useStorage from '../utils/storageHook';
import { ToastContainer, toast } from 'react-toastify';

import { obtenerSesion, actualizarEmpresaSesion } from '../services/Usuarios';
import { obtenerEmpresas, eliminarEmpresa } from '../services/Empresas';

import 'react-toastify/dist/ReactToastify.min.css';

function Home() {

  const { getItem, setItem, removeItem } = useStorage();
  const jwt = getItem('token');
  const router = useRouter();
  const [usuario, setUsuario] = useState(null)
  const [empresas, setEmpresas] = useState({
      data: [],
      monedas: []
  })
  const [idEmpresa, setIdEmpresa] = useState('');
  const [modalform, setModalform] = useState({
    open:false,
    tipo:'nuevo',
    datos:null
  });
  const [openDialog, setOpenDialog] = useState(false);

  const cargarDatos = async () =>{
      let emp = await obtenerEmpresas(jwt);
      if(emp.ok){
        if(emp.data.length > 0) setIdEmpresa(emp.data[emp.data.length-1].idempresa)
        setEmpresas({
          data: emp.data,
          monedas: emp.monedas
        });
      }else{
        console.log(emp.mensaje)
      }
  }

  const cargarUsuario = async () =>{
    let sesion = await obtenerSesion(jwt);
    if(sesion.ok){
      setUsuario(sesion.data);
    }
}

  useEffect(() => {
      if(jwt == undefined){
        router.push('/login')
        return (<div>Loading...</div>)
      }else{
        cargarUsuario()
        cargarDatos();
      }
  }, []);

  const handleChange = (event) => {
    setIdEmpresa(event.target.value);
  };
  const handleNuevo = () => {
    setModalform({
      open:true,
      tipo:'nuevo',
      datos:null
    });
  };
  const handleCloseModal = () => {
    setModalform({
      open:false,
      tipo:'nuevo',
      datos:null
    });
  };
  const handleEditar = () =>{
    setModalform({
      open:true,
      tipo:'editar',
      datos:empresas.data.find(x => x.idempresa === idEmpresa)
    });
  }
  const handleSubmit = () =>{
    cargarDatos();
  }

  const handleEliminar= async () =>{
    let eliminar = await eliminarEmpresa(idEmpresa, jwt);
    if(eliminar.ok){
      handleSubmit();
      setOpenDialog(false);
    }else{
      toast.error(eliminar.mensaje,{theme: "colored"});
    }
  }


  const handleReport= () =>{
    window.open(`http://localhost:8080/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2Freports&reportUnit=%2Freports%2FEmpresas&standAlone=true&id_usuario=${usuario.idusuario}&j_username=joeuser&j_password=123&sessionDecorator=no`, '_blank');
  }

  const logout = async () => {
    removeItem('token')
    router.push('/login')
  }

  const saveSession = async () => {
    let data = {
      idempresa: idEmpresa
    }
    let session = await actualizarEmpresaSesion(data, jwt);
      if(session.ok){
        setItem('token',session.token)
        router.push('/dashboard')
      }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Empresas | ERP</title>
        <meta name="description" content="ERP Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main" sx={{ alignItems: 'center', display: 'flex', flexGrow: 1, minHeight: '100vh' }}>
      {usuario && <Container maxWidth="sm">
            <Box sx={{pb: 1,pt: 3}}>
              <Typography align="center" color="textSecondary" variant="h2">
                Bienvenido {usuario.nombre}
              </Typography>
            </Box>
            <Box sx={{ py: 2 , textAlign:'center'}}>
              <TextField id="outlined-select-empresa" select label="Seleccione una Empresa" value={idEmpresa} onChange={handleChange} helperText="Por favor selecciona una empresa" sx={{ textAlign:'center', width:'300px'}} >
                  {empresas.data.map((option,i) => (
                    <MenuItem key={option.idempresa} value={option.idempresa}>
                      {option.nombre}
                    </MenuItem>
                  ))}
                </TextField>
                <Button sx={{ mx: 2, height: '56px' }} color="success" size="large" variant="contained" disabled={idEmpresa==="" ? true : false} onClick={saveSession} ><LoginRoundedIcon/></Button>
            </Box>
            <Box sx={{ py: 2 , textAlign:'center'}}>
                <Button sx={{ mx: 2 }} color="primary" size="large" variant="contained" onClick={handleNuevo} ><AddBusinessRoundedIcon/></Button>
                <Button sx={{ mx: 2 }} color="warning" size="large" variant="contained" disabled={idEmpresa==="" ? true : false} onClick={handleEditar}><EditRoundedIcon/></Button>
                <Button sx={{ mx: 2}} color="error" size="large" variant="contained" onClick={()=>{setOpenDialog(true)}} disabled={idEmpresa===""}><DeleteForeverRoundedIcon/></Button>
                <Button sx={{ mx: 2}} color="secondary" size="large" variant="contained" onClick={handleReport}><AssignmentRoundedIcon/></Button>          
            </Box>
            <Box sx={{ py: 2 , textAlign:'center'}}>
              <Button color="error" onClick={logout}><PowerSettingsNewRoundedIcon/>{' '}Cerrar Sesion</Button>
            </Box>
        </Container>
        /*: <Container maxWidth="sm">Loading...</Container>*/}
      </Box>
      <ModalForm open={modalform.open} tipo={modalform.tipo} datos={modalform.datos} monedas={empresas.monedas} close={handleCloseModal} submit={handleSubmit} jwt={jwt} ></ModalForm>
      <AlertDialog open={openDialog} title={"¿Seguro que desea eliminar esta empresa?"} body={"La empresa no se podrá volver a recuperar"} btnText={"Eliminar"} close={() => setOpenDialog(false)} confirm={handleEliminar} />
      <ToastContainer position="top-right" autoClose={3000} hideProgressBar newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable={false} pauseOnHover />
    </div>
  )
}


export default Home


Home.getLayout = function getLayout(page) {
  return (
    <ThemeProvider theme={theme}>
        <CssBaseline />
          {page}
    </ThemeProvider>
  )
}